### ISSUE TITLE
New Tinder regulation

### ISSUE THREAD

**Issue by KLVN** [MrPing/Flamite-old#11]
Sadly Tinder is now forcing to update to the newest version that comes with limitations. I can like only 110 User per 24h...
I found Flamite 2 days ago and can say that it's a really great Bot, but now you have to buy Tinder Plus for 11€/month to use Flamite for mass-liking :/

**Comment by Fogest** [comment]
Is this on iOS? I have no update on Android yet.

**Comment by KLVN** [comment]
It appeard on Android and even I didn't updated to the latest version. Suddenly the interface changed and the like-limit was active

**Comment by Fogest** [comment]
I don't see anything in the app itself indicating this. Is there nothing that tells the user about this change in the app? Do you have to get to 110 users before you find out about the restriction? Just curious how it works.

**Comment by KLVN** [comment]
The design changed: New Tinder has 4 Buttons (Like, Nope, Change Location and Undo)
I've Version 4.0.4 installed.

**Comment by Fogest** [comment]
Oh wow. I guess I'll be getting that new interface once it rolls out to me.
Undo is now non premium?

**Comment by KLVN** [comment]
"Undo is now non premium?"

- No. Only for Premium.


http://techcrunch.com/2015/02/02/tinder-plus-the-paid-version-featuring-an-undo-button-and-more-arrives-in-u-s-next-month/#akxCgj:pjP

**Comment by Fogest** [comment]
Oh wow the update won't be in place across all of US until mid march. I'm
not even in the US, I'm in Canada so it may even be much longer! Awesome!

Justin V

**Comment by KLVN** [comment]
Found a glitch: If you turn off Discovery there's no limitation of likes! Flamite already liked 300 profiles and it's still running.

**Comment by MrPing** [comment]
be careful, Tinder detects getting better the mass-liking, it is risky to use the booster.

**Comment by MrPing** [comment]
I suggest you stay in manual mode.

**Comment by Fogest** [comment]
@MrPing what do they do if they detect it? Curious how I know if they have detected it for me or not? Does flammite give any error? If I have the random dislike on while using the slow speed does Tinder still stop you?
